#lang racket

(require "music-language.rkt")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Test cases ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; Songs
;; Mester jacob
(define instrument-1 'guitar)
(define instrument-2 'piano)
(define instrument-3 'flute)
(define mester-jacob (sequentiel (list (note 'F 5 1/2 instrument-2)
                                       (note 'G 5 1/2 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'G 5 1/2 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'A# 5 1/2 instrument-2)
                                       (note 'C 6 1/1 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'A# 5 1/2 instrument-2)
                                       (note 'C 6 1/1 instrument-2)
                                       (note 'C 6 1/4 instrument-2)
                                       (note 'D 6 1/4 instrument-2)
                                       (note 'C 6 1/4 instrument-2)
                                       (note 'A# 5 1/4 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'C 6 1/4 instrument-2)
                                       (note 'D 6 1/4 instrument-2)
                                       (note 'C 6 1/4 instrument-2)
                                       (note 'A# 5 1/4 instrument-2)
                                       (note 'A 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'C 5 1/2 instrument-2)
                                       (note 'F 5 1/1 instrument-2)
                                       (note 'F 5 1/2 instrument-2)
                                       (note 'C 5 1/2 instrument-2)
                                       (note 'F 5 1/1 instrument-2))))
 
(define mester-jacob-canon (parallel (list mester-jacob
                                           (sequentiel (list (pause 4)
                                                             (change-instrument (transpose mester-jacob 12) instrument-3)))
                                           (sequentiel (list (pause 8)
                                                             (change-instrument (transpose mester-jacob -12) instrument-1))))))
;; Viva la Musica
(define viva-la-musica-1 (list (note 'C 6 3/8 instrument-1)
                               (note 'A# 5 1/8 instrument-1)
                               (note 'A 5 1/4 instrument-1)
                               (note 'G 5 1/8 instrument-1)
                               (note 'F 5 1/8 instrument-1)
                               (note 'D 5 1/4 instrument-1)
                               (note 'F 5 1/4 instrument-1)
                               (note 'D 5 1/2 instrument-1)))
(define viva-la-musica-2 (list (note 'A 5 3/8 instrument-2)
                               (note 'A# 5 1/8 instrument-2)
                               (note 'C 6 1/4 instrument-2)
                               (note 'A# 5 1/8 instrument-2)
                               (note 'A 5 1/8 instrument-2)
                               (note 'G 5 1/4 instrument-2)
                               (note 'F 5 1/4 instrument-2)
                               (note 'G 5 1/2 instrument-2)))
(define viva-la-musica-3 (list (note 'F 5 1/4 instrument-3)
                               (note 'F 5 1/2 instrument-3)
                               (note 'A# 4 1/4 instrument-3)
                               (note 'C 5 1/4 instrument-3)
                               (note 'D 5 1/4 instrument-3)
                               (note 'C 5 1/2 instrument-3)))
(define viva-la-musica (list viva-la-musica-1 viva-la-musica-2 viva-la-musica-3))

;; Making a song
(transform-to-midi-file-and-write-to-file! (ready-for-midi (get-absolute-timed-notes-of (multiply-duration (make-canon viva-la-musica 1) 3))) "Test-song")

;; other tests
(define seq-with-para-para (sequentiel (list (parallel (list (note 'C 4 9 'telephone)
                                                             (note 'C 4 1 'telephone)))
                                             (parallel (list (note 'C 4 1 'organ)
                                                             (note 'C 4 1 'organ))))))
(define i (sequentiel (list (note 'C 4 2 'piano)
                            (pause 20)
                            (note 'F# 7 3/4 'violin)
                            (parallel (list (note 'C 4 2 'piano)
                                            (pause 20)
                                            (note 'F# 7 3/4 'violin)
                                            (sequentiel (list (note 'C 4 2 'piano)
                                                        (pause 20)
                                                        (note 'F# 7 3/4 'violin))))))))
(define j (sequentiel (list (note 'C 4 2 'piano)
                            (pause 20)
                            (note 'F# 7 3/4 'violin)
                            (parallel (list (note 'C 4 2 'piano)
                                            (pause 20)
                                            (note 'F# 7 3/4 'violin)
                                            (parallel (list (note 'C 4 2 'piano)
                                                            (pause 20)
                                                            (note 'F# 7 3/4 'violin))))))))
(define k (parallel (list (note 'C 4 2 'piano)
                          (pause 20)
                          (note 'F# 7 3/4 'violin))))
(define m (sequentiel (list (note 'C 4 2 'piano)
                            (pause 20)
                            (note 'F# 7 3/4 'violin))))
(define n (note 'C 4 2 'piano))
(define p (pause 20))

;(define i- (ready-for-midi (get-absolute-timed-notes-of (multiply-duration (viva-la-musica-setup-2 1) 3))))
;(define i- (ready-for-midi (get-absolute-timed-notes-of (multiply-duration viva-la-musica 3))))
;(define i- (ready-for-midi (get-absolute-timed-notes-of seq-with-para-para)))
(define i- (ready-for-midi (get-absolute-timed-notes-of (multiply-duration mester-jacob-canon 2))))
(define t (get-absolute-timed-notes-of seq-with-para-para))
;(transform-to-midi-file-and-write-to-file! i- "that")
